Model <- readRDS("Data/LatestModel.rds")
countsRep <- cor(Model$Input$counts[,-1], method = 'pearson')
ori_Name <- c("REP","Meljuso","TIGI1_004","TIPK1","TIMEL202_003","HS944")
sub_Name <- c("Rep","MELJUSO","GI1","PK1","MEL202","HS944T")
colnames(countsRep)%<>%mgsub::mgsub(.,ori_Name,sub_Name)
rownames(countsRep)%<>%mgsub::mgsub(.,ori_Name,sub_Name)
sort(rownames(countsRep))
pdf(paste0("Fig S2a Paralog screen replicate correlation/FigS2a_Replicate_LFC_correlation_",Sys.Date(),".pdf"), width = 10, height = 9)
pheatmap::pheatmap(mat = countsRep,
                   color = colorRampPalette(c("white","gray", "#FFAAAA", "#FF6666"))(100))
dev.off()